# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += gui src
TEMPLATE = subdirs

# CONFIG -= relase
# CONFIG += debug



